name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [Debug, Release]
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v3
    
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DCMAKE_CXX_COMPILER=${{matrix.compiler}}
    
    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build_type}}
    
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C ${{matrix.build_type}} --output-on-failure
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-${{matrix.build_type}}-${{matrix.compiler}}
        path: ${{github.workspace}}/build/
    
    - name: Run clang-tidy
      if: matrix.compiler == 'clang'
      run: |
        sudo apt-get update
        sudo apt-get install -y clang-tidy
        cmake --build ${{github.workspace}}/build --target clang-tidy

  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cppcheck
    
    - name: Run cppcheck
      run: cppcheck --enable=all --error-exitcode=1 src/
    
    - name: Run clang-format check
      run: |
        sudo apt-get install -y clang-format
        find src/ -name '*.cpp' -o -name '*.hpp' | xargs clang-format --dry-run -Werror 